### PR TITLE
Fixes #547. Invite: validate email field

### LINKED ISSUE #547: [Collaborators] Email field is not being validated
The user can input anything, and an email will try to be sent to the wrong email address.

screen shot 2017-01-13 at 3 26 32 pm

screen shot 2017-01-13 at 3 25 26 pm

### PR DESCRIPTION
**Pull request by lmatayoshi**
Fixes #547

### CODE REVIEW

File: web/static/js/reducers/guest.js [hunk 1]
```diff
@@ -18,18 +21,31 @@ export default (state = initialState, action) => {
...
+    errors: {
+      ...state.errors,
+      email: !validEmail(action.email)
+    }
   }
 }
 
 const changeLevel = (state, action) => {
   if (['reader', 'editor'].includes(action.level)) {
+    const newData = {...state.data}
```
Comment (juanboca) [inline web/static/js/reducers/guest.js]: Here you should avoid defining a `const` and use a spread to define the new data
